const router = require("express").Router();
const { permit } = require('../middlewares/auth.middleware');
const { ADMIN, INSTRUCTOR, STUDENT } = require('../constants/roles.constant');
let controller = require("../controllers/niveau.controller");
router.get("/", permit(STUDENT, INSTRUCTOR, ADMIN), controller.getAll);
router.get("/getAllForUsers", controller.getAllForUsers);
router.get("/:id", permit(STUDENT, INSTRUCTOR, ADMIN), controller.findById);
router.get("/search/:query", permit(STUDENT, INSTRUCTOR, ADMIN), controller.search);
router.get("/getSeeMoreByNiveauId/:nivId/:nivMatId", permit(STUDENT, INSTRUCTOR, ADMIN), controller.getSeeMoreByNiveauId);
router.get("/withMatieres/:id", permit(STUDENT, INSTRUCTOR, ADMIN), controller.withMatieres);
router.get("/getAllMatieresById/:id", permit(STUDENT, INSTRUCTOR, ADMIN), controller.getAllMatieresById);
router.get("/getMatiereByNivMatId/:id", permit(STUDENT, INSTRUCTOR, ADMIN), controller.getMatiereByNivMatId);
router.post("/", permit(INSTRUCTOR, ADMIN), controller.createNiv);
router.post("/createNivMat", permit(INSTRUCTOR, ADMIN), controller.createNivMat);
router.put("/editNivsOrders", permit(INSTRUCTOR, ADMIN), controller.editNivsOrders);
router.put("/editMatieresOrders", permit(INSTRUCTOR, ADMIN), controller.editMatieresOrders);
router.put("/editNivMatById/:id", permit(INSTRUCTOR, ADMIN), controller.editNivMatById);
router.put("/:id", permit(INSTRUCTOR, ADMIN), controller.updateById);
router.delete("/:id", permit(INSTRUCTOR, ADMIN), controller.deleteNivById);
router.delete("/deleteNivMat/:id", permit(INSTRUCTOR, ADMIN), controller.deleteNivMatById);
module.exports = router;
